-- SQL Patch Script for `patients` Table

-- Add missing columns to the `patients` table
ALTER TABLE patients ADD COLUMN IF NOT EXISTS first_name TEXT;
ALTER TABLE patients ADD COLUMN IF NOT EXISTS last_name TEXT;
ALTER TABLE patients ADD COLUMN IF NOT EXISTS email TEXT;
ALTER TABLE patients ADD COLUMN IF NOT EXISTS phone TEXT;
ALTER TABLE patients ADD COLUMN IF NOT EXISTS date_of_birth DATE;
ALTER TABLE patients ADD COLUMN IF NOT EXISTS address TEXT;
ALTER TABLE patients ADD COLUMN IF NOT EXISTS city TEXT;
ALTER TABLE patients ADD COLUMN IF NOT EXISTS medical_notes TEXT;
ALTER TABLE patients ADD COLUMN IF NOT EXISTS referral_source_id UUID;
ALTER TABLE patients ADD COLUMN IF NOT EXISTS referred_by_patient_id UUID;
ALTER TABLE patients ADD COLUMN IF NOT EXISTS partner_id UUID;
ALTER TABLE patients ADD COLUMN IF NOT EXISTS blood_test_done BOOLEAN;
ALTER TABLE patients ADD COLUMN IF NOT EXISTS created_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE patients ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP WITH TIME ZONE;